version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - pg_db:/opt/sonarqube/pg_db
      - pg_data:/opt/sonarqube/pg_data
    networks:
      - sonar_network
    deploy:
      placement:
        constraints: [node.role == manager]

  sonarqube:
    image: sonarqube:9.9.8-community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_SEARCH_JAVAADDITIONALOPTS: -Dbootstrap.system_call_filter=false
    ports:
      - "9000:9000"
    volumes:
      - sonar_logs:/opt/sonarqube/logs
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    networks:
      - sonar_network
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  pg_db:
  pg_data:
  sonar_logs:
  sonar_data:
  sonar_extensions:

networks:
  sonar_network:
    driver: overlay
