version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    hostname: jenkins
    ports:
      - 8080:8080
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
